require_relative "vagrant_plugin_guest_busybox.rb"
if (Vagrant::Errors::LinuxNFSMountFailed rescue false) # Vagrant <= 1.8.4
  require_relative "mount_nfs.rb"
end
require_relative "prepare_nfs_settings.rb"

Vagrant.configure("2") do |config|
  config.ssh.username = "bargee"

  # Forward the Docker port
  config.vm.network :forwarded_port, guest: 2375, host: 2375, auto_correct: true

  # Disable synced folder by default
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
