# A dummy plugin for Barge to set hostname and network correctly at the very first `vagrant up`
module VagrantPlugins
  module GuestLinux
    class Plugin < Vagrant.plugin("2")
      guest_capability("linux", "change_host_name") { Cap::ChangeHostName }
      guest_capability("linux", "configure_networks") { Cap::ConfigureNetworks }
    end
  end
end

Vagrant.configure(2) do |config|
  config.vm.define "barge-secure"

  config.vm.box = "ailispaw/barge"

  config.vm.network :forwarded_port, guest: 2375, host: 2375, auto_correct: true, disabled: true
  config.vm.network :forwarded_port, guest: 2376, host: 2376, auto_correct: true

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision :shell, path: "generate_certs.sh"

  config.vm.provision :shell do |sh|
    sh.privileged = false
    sh.inline = <<-EOT
      cp -R ~/.docker /vagrant/
      sudo /etc/init.d/docker restart
    EOT
  end
end
